services:
  - type: web
    name: univent-backend
    env: python
    region: singapore
    buildCommand: ./build.sh
    startCommand: gunicorn api.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        value: aws-0-ap-southeast-1.pooler.supabase.com
      - key: DB_PORT
        value: 6543
      - key: DB_NAME
        value: postgres
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    buildpacks:
      - name: python
      - name: apt
    packages:
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - gcc
      - libpq-dev
      - libjpeg-dev
      - zlib1g-dev
